version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
