version: "3.8"

services:
  frontend:
    image: adrienbarb/goodtobenaked-frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api.nastynipples.com
    secrets:
      - NEXTAUTH_URL
      - GOOGLE_PLACE_API_KEY
      - ADMIN_PRIVATE_KEY
      - NEXTAUTH_SECRET
      - NEXT_PUBLIC_CLOUDFRONT_MEDIA
    ports:
      - "3000:3000"
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  backend:
    image: adrienbarb/goodtobenaked-backend:latest
    environment:
      - NODE_ENV=production
      - MONGO_URL=/run/secrets/MONGODB_URI
    secrets:
      - JWT_SECRET
      - MONGODB_URI
      - INTERNAL_CLIENT_URL
      - CLIENT_URL
      - MAIL_GUN_API_KEY
      - MAIL_GUN_BASE_URL
      - ADMIN_PRIVATE_KEY
      - STRIPE_API_KEY
      - NOTION_API_KEY
      - CLOUDFRONT_URL
      - SLACK_TOKEN
      - MAILCHIMP_API_KEY
      - S3_BUCKET_MEDIA
      - S3_BUCKET_PROCESSED_MEDIA
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_ENDPOINT_SECRET
    ports:
      - "3001:3001"
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

secrets:
  JWT_SECRET:
    external: true
  MONGODB_URI:
    external: true
  INTERNAL_CLIENT_URL:
    external: true
  CLIENT_URL:
    external: true
  MAIL_GUN_API_KEY:
    external: true
  MAIL_GUN_BASE_URL:
    external: true
  ADMIN_PRIVATE_KEY:
    external: true
  STRIPE_API_KEY:
    external: true
  NOTION_API_KEY:
    external: true
  CLOUDFRONT_URL:
    external: true
  SLACK_TOKEN:
    external: true
  MAILCHIMP_API_KEY:
    external: true
  S3_BUCKET_MEDIA:
    external: true
  S3_BUCKET_PROCESSED_MEDIA:
    external: true
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  AWS_REGION:
    external: true
  STRIPE_PUBLISHABLE_KEY:
    external: true
  STRIPE_ENDPOINT_SECRET:
    external: true
  NEXTAUTH_URL:
    external: true
  GOOGLE_PLACE_API_KEY:
    external: true
  NEXTAUTH_SECRET:
    external: true
  NEXT_PUBLIC_CLOUDFRONT_MEDIA:
    external: true

networks:
  app-network:
    external: true
