version: "3.8"

services:
  traefik:
    image: traefik:v2.6
    command:
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.websecure.address=:8443"
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=adrien-barbier@hotmail.fr"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/acme.json"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--log.level=DEBUG"
    ports:
      - "8081:8081"
      - "8443:8443"
      - "8080:8080" # Pour accéder au tableau de bord
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.nastynipples.com`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certResolver=mytlschallenge"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

  frontend:
    image: adrienbarb/goodtobenaked-frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api.nastynipples.com
    secrets:
      - NEXTAUTH_URL
      - GOOGLE_PLACE_API_KEY
      - ADMIN_PRIVATE_KEY
      - NEXTAUTH_SECRET
      - NEXT_PUBLIC_CLOUDFRONT_MEDIA
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`nastynipples.com`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certResolver=mytlschallenge"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  backend:
    image: adrienbarb/goodtobenaked-backend:latest
    environment:
      - NODE_ENV=production
      - MONGO_URL=/run/secrets/MONGODB_URI
    secrets:
      - JWT_SECRET
      - MONGODB_URI
      - INTERNAL_CLIENT_URL
      - CLIENT_URL
      - MAIL_GUN_API_KEY
      - MAIL_GUN_BASE_URL
      - ADMIN_PRIVATE_KEY
      - STRIPE_API_KEY
      - NOTION_API_KEY
      - CLOUDFRONT_URL
      - SLACK_TOKEN
      - MAILCHIMP_API_KEY
      - S3_BUCKET_MEDIA
      - S3_BUCKET_PROCESSED_MEDIA
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_ENDPOINT_SECRET
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.nastynipples.com`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certResolver=mytlschallenge"
        - "traefik.http.services.backend.loadbalancer.server.port=3001"

secrets:
  JWT_SECRET:
    external: true
  MONGODB_URI:
    external: true
  INTERNAL_CLIENT_URL:
    external: true
  CLIENT_URL:
    external: true
  MAIL_GUN_API_KEY:
    external: true
  MAIL_GUN_BASE_URL:
    external: true
  ADMIN_PRIVATE_KEY:
    external: true
  STRIPE_API_KEY:
    external: true
  NOTION_API_KEY:
    external: true
  CLOUDFRONT_URL:
    external: true
  SLACK_TOKEN:
    external: true
  MAILCHIMP_API_KEY:
    external: true
  S3_BUCKET_MEDIA:
    external: true
  S3_BUCKET_PROCESSED_MEDIA:
    external: true
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  AWS_REGION:
    external: true
  STRIPE_PUBLISHABLE_KEY:
    external: true
  STRIPE_ENDPOINT_SECRET:
    external: true
  NEXTAUTH_URL:
    external: true
  GOOGLE_PLACE_API_KEY:
    external: true
  NEXTAUTH_SECRET:
    external: true
  NEXT_PUBLIC_CLOUDFRONT_MEDIA:
    external: true

networks:
  app-network:
    external: true
