# Étape 1 : Construction de l'application React
FROM node:18-alpine AS build

# Définir le répertoire de travail pour le client React
WORKDIR /app/client

# Copier les fichiers package.json et package-lock.json spécifiques au client
COPY client/package.json client/package-lock.json ./

# Installer les dépendances du client
RUN npm install

# Copier les fichiers sources du client
COPY client/ .

# Construire l'application React
RUN npm run build

# Étape 2 : Construction de l'application backend
FROM node:18-alpine

# Définir le répertoire de travail pour le backend
WORKDIR /app

# Copier les fichiers package.json et package-lock.json spécifiques au backend
COPY package.json package-lock.json ./

# Installer les dépendances du backend y compris les devDependencies
RUN npm install --only=development && npm cache clean --force

# Copier les fichiers sources du backend
COPY . .

# Copier les fichiers de build de React générés lors de la première étape
COPY --from=build /app/client/build /app/client/build

# Installer les dépendances du client React
WORKDIR /app/client
RUN npm install

# Définir le répertoire de travail pour le backend à nouveau
WORKDIR /app

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3001

# Installer les outils nécessaires pour le développement
RUN npm install -g nodemon

# Commande à exécuter lorsque le conteneur est démarré
CMD ["npm", "run", "dev"]
