export const sexeValues = [
  { value: "male", label: "Homme" },
  { value: "female", label: "Femme" },
];

export const ageValues = Array(82)
  .fill(1)
  .map((n, i) => i + 18);

export const breastSize = ["A", "B", "C", "D", "E", "F", "G"];

export const buttSize = ["small", "normal", "big", "huge"];

export const BODY_TYPE = [
  "ideal_for_a_câlin",
  "tender_like_a_marshmallow",
  "perfectly_proportioned",
  "all_rounded",
  "thin_as_a_feather",
  "tonic_like_a_lemon",
  "sculpted_like_a_greek_statue",
  "graceful_like_a_flamingo",
  "slim_as_a_matchstick",
  "strong_as_a_lumberjack",
  "compact_like_a_Rubik_s_Cube",
];

export const HAIR_COLOR = ["black", "blonde", "brunette", "redhead", "others"];

export const countries = [
  { label: "afghanistan", value: "af" },
  { label: "albania", value: "al" },
  { label: "algeria", value: "dz" },
  { label: "andorra", value: "ad" },
  { label: "angola", value: "ao" },
  { label: "antigua_and_barbuda", value: "ag" },
  { label: "argentina", value: "ar" },
  { label: "armenia", value: "am" },
  { label: "australia", value: "au" },
  { label: "austria", value: "at" },
  { label: "azerbaijan", value: "az" },
  { label: "bahamas", value: "bs" },
  { label: "bahrain", value: "bh" },
  { label: "bangladesh", value: "bd" },
  { label: "barbados", value: "bb" },
  { label: "belarus", value: "by" },
  { label: "belgium", value: "be" },
  { label: "belize", value: "bz" },
  { label: "benin", value: "bj" },
  { label: "bhutan", value: "bt" },
  { label: "bolivia", value: "bo" },
  { label: "bosnia_and_herzegovina", value: "ba" },
  { label: "botswana", value: "bw" },
  { label: "brazil", value: "br" },
  { label: "brunei", value: "bn" },
  { label: "bulgaria", value: "bg" },
  { label: "burkina_faso", value: "bf" },
  { label: "burundi", value: "bi" },
  { label: "cabo_verde", value: "cv" },
  { label: "cambodia", value: "kh" },
  { label: "cameroon", value: "cm" },
  { label: "canada", value: "ca" },
  { label: "central_african_republic", value: "cf" },
  { label: "chad", value: "td" },
  { label: "chile", value: "cl" },
  { label: "china", value: "cn" },
  { label: "colombia", value: "co" },
  { label: "comoros", value: "km" },
  { label: "congo_democratic_republic", value: "cd" },
  { label: "congo_republic", value: "cg" },
  { label: "costa_rica", value: "cr" },
  { label: "croatia", value: "hr" },
  { label: "cuba", value: "cu" },
  { label: "cyprus", value: "cy" },
  { label: "czech_republic", value: "cz" },
  { label: "denmark", value: "dk" },
  { label: "djibouti", value: "dj" },
  { label: "dominica", value: "dm" },
  { label: "dominican_republic", value: "do" },
  { label: "ecuador", value: "ec" },
  { label: "egypt", value: "eg" },
  { label: "el_salvador", value: "sv" },
  { label: "equatorial_guinea", value: "gq" },
  { label: "eritrea", value: "er" },
  { label: "estonia", value: "ee" },
  { label: "eswatini", value: "sz" },
  { label: "ethiopia", value: "et" },
  { label: "fiji", value: "fj" },
  { label: "finland", value: "fi" },
  { label: "france", value: "fr" },
  { label: "gabon", value: "ga" },
  { label: "gambia", value: "gm" },
  { label: "georgia", value: "ge" },
  { label: "germany", value: "de" },
  { label: "ghana", value: "gh" },
  { label: "greece", value: "gr" },
  { label: "grenada", value: "gd" },
  { label: "guatemala", value: "gt" },
  { label: "guinea", value: "gn" },
  { label: "guinea-bissau", value: "gw" },
  { label: "guyana", value: "gy" },
  { label: "haiti", value: "ht" },
  { label: "honduras", value: "hn" },
  { label: "hungary", value: "hu" },
  { label: "iceland", value: "is" },
  { label: "india", value: "in" },
  { label: "indonesia", value: "id" },
  { label: "iran", value: "ir" },
  { label: "iraq", value: "iq" },
  { label: "ireland", value: "ie" },
  { label: "israel", value: "il" },
  { label: "italy", value: "it" },
  { label: "jamaica", value: "jm" },
  { label: "japan", value: "jp" },
  { label: "jordan", value: "jo" },
  { label: "kazakhstan", value: "kz" },
  { label: "kenya", value: "ke" },
  { label: "kiribati", value: "ki" },
  { label: "kuwait", value: "kw" },
  { label: "kyrgyzstan", value: "kg" },
  { label: "laos", value: "la" },
  { label: "latvia", value: "lv" },
  { label: "lebanon", value: "lb" },
  { label: "lesotho", value: "ls" },
  { label: "liberia", value: "lr" },
  { label: "libya", value: "ly" },
  { label: "liechtenstein", value: "li" },
  { label: "lithuania", value: "lt" },
  { label: "luxembourg", value: "lu" },
  { label: "madagascar", value: "mg" },
  { label: "malawi", value: "mw" },
  { label: "malaysia", value: "my" },
  { label: "maldives", value: "mv" },
  { label: "mali", value: "ml" },
  { label: "malta", value: "mt" },
  { label: "marshall_islands", value: "mh" },
  { label: "mauritania", value: "mr" },
  { label: "mauritius", value: "mu" },
  { label: "mexico", value: "mx" },
  { label: "micronesia", value: "fm" },
  { label: "moldova", value: "md" },
  { label: "monaco", value: "mc" },
  { label: "mongolia", value: "mn" },
  { label: "montenegro", value: "me" },
  { label: "morocco", value: "ma" },
  { label: "mozambique", value: "mz" },
  { label: "myanmar", value: "mm" },
  { label: "namibia", value: "na" },
  { label: "nauru", value: "nr" },
  { label: "nepal", value: "np" },
  { label: "netherlands", value: "nl" },
  { label: "new_zealand", value: "nz" },
  { label: "nicaragua", value: "ni" },
  { label: "niger", value: "ne" },
  { label: "nigeria", value: "ng" },
  { label: "north_korea", value: "kp" },
  { label: "north_macedonia", value: "mk" },
  { label: "norway", value: "no" },
  { label: "oman", value: "om" },
  { label: "pakistan", value: "pk" },
  { label: "palau", value: "pw" },
  { label: "panama", value: "pa" },
  { label: "papua_new_guinea", value: "pg" },
  { label: "paraguay", value: "py" },
  { label: "peru", value: "pe" },
  { label: "philippines", value: "ph" },
  { label: "poland", value: "pl" },
  { label: "portugal", value: "pt" },
  { label: "qatar", value: "qa" },
  { label: "romania", value: "ro" },
  { label: "russia", value: "ru" },
  { label: "rwanda", value: "rw" },
  { label: "saint_kitts_and_nevis", value: "kn" },
  { label: "saint_lucia", value: "lc" },
  { label: "saint_vincent_and_the_grenadines", value: "vc" },
  { label: "samoa", value: "ws" },
  { label: "san_marino", value: "sm" },
  { label: "sao_tome_and_principe", value: "st" },
  { label: "saudi_arabia", value: "sa" },
  { label: "senegal", value: "sn" },
  { label: "serbia", value: "rs" },
  { label: "seychelles", value: "sc" },
  { label: "sierra_leone", value: "sl" },
  { label: "singapore", value: "sg" },
  { label: "slovakia", value: "sk" },
  { label: "slovenia", value: "si" },
  { label: "solomon_islands", value: "sb" },
  { label: "somalia", value: "so" },
  { label: "south_africa", value: "za" },
  { label: "south_korea", value: "kr" },
  { label: "south_sudan", value: "ss" },
  { label: "spain", value: "es" },
  { label: "sri_lanka", value: "lk" },
  { label: "sudan", value: "sd" },
  { label: "suriname", value: "sr" },
  { label: "sweden", value: "se" },
  { label: "switzerland", value: "ch" },
  { label: "syria", value: "sy" },
  { label: "taiwan", value: "tw" },
  { label: "tajikistan", value: "tj" },
  { label: "tanzania", value: "tz" },
  { label: "thailand", value: "th" },
  { label: "timor_leste", value: "tl" },
  { label: "togo", value: "tg" },
  { label: "tonga", value: "to" },
  { label: "trinidad_and_tobago", value: "tt" },
  { label: "tunisia", value: "tn" },
  { label: "turkey", value: "tr" },
  { label: "turkmenistan", value: "tm" },
  { label: "tuvalu", value: "tv" },
  { label: "uganda", value: "ug" },
  { label: "ukraine", value: "ua" },
  { label: "united_arab_emirates", value: "ae" },
  { label: "united_kingdom", value: "gb" },
  { label: "united_states", value: "us" },
  { label: "uruguay", value: "uy" },
  { label: "uzbekistan", value: "uz" },
  { label: "vanuatu", value: "vu" },
  { label: "vatican_city", value: "va" },
  { label: "venezuela", value: "ve" },
  { label: "vietnam", value: "vn" },
  { label: "yemen", value: "ye" },
  { label: "zambia", value: "zm" },
  { label: "zimbabwe", value: "zw" },
];

export const material = [
  "lycra",
  "cotton",
  "synthetic",
  "leather",
  "latex",
  "lace",
  "microfiber",
  "nylon",
  "polyester",
  "silk",
  "satin",
  "others",
];

export const duration = ["24h", "48h", "72h", "72h+"];

export const activity = ["sport", "sexe", "masturbation", "others"];
