import { Notification } from "../notification";
import { Address } from "./Address";
import { Gender } from "./genderModel";
import { ShippingFee } from "./shippingFee";

export interface Creator {
  _id: string;
  firstname?: string;
  lastname?: string;
  pseudo: string;
  email: string;
  password: string;
  gender?: Gender;
  profilPicture?: string;
  bannerPicture?: string;
  emailNotification?: boolean;
  description?: string;
  twitterLink?: string;
  instagramLink?: string;
  mymLink?: string;
  onlyfansLink?: string;
  nationality?: string;
  breastSize?: "tiny" | "normal" | "big" | "huge";
  buttSize?: "small" | "normal" | "big" | "huge";
  bodyType?: "skinny" | "athletic" | "medium" | "curvy";
  hairColor?: "black" | "blonde" | "brunette" | "redhead";
  age?: number;
  verified?: "unverified" | "rejected" | "pending" | "verified";
  emailVerified?: boolean;
  tags?: string[];
  rate?: number;
  rateCount?: number;
  country?: string;
  salesFee?: number;
  address?: Address;
  bankAccountName?: string;
  bankAccountIBAN?: string;
  automaticPayment?: boolean;
  invoices?: any[];
  invoiceAddress?: Address;
  shippingCarriers?: string[];
  anonymous?: boolean;
  isAmbassador: boolean;
  smallPackageDeliveryCost?: number;
  mediumPackageDeliveryCost?: number;
  bigPackageDeliveryCost?: number;
  completionProfilNotification?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  shippingFees: ShippingFee[];
  inappNotification: Notification[];
  referrals: Creator[];
  version: number;
  lastLogin: Date;
  notificationSubscribers: string[];
}
